name: Selenium Firefox Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        sudo apt-get update
        sudo apt-get install firefox
    - name: Run tests
      env:
        MYZIP_PASSWORD: ${{ secrets.MYZIP_PASSWORD }} 
      run: |
        python scra.py

    - name: commit and push channels.zip
      run: |
        git config --global user.name "${{ secrets.USERNAME_GITHUB }}"
        git config --global user.email "${{ secrets.EMAIL_GITHUB }}"
        git add channels.zip
        git commit -m "updated channels.zip"
        git push
