name: Selenium Firefox Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        sudo apt-get update
        sudo apt-get install firefox
      env:
        MYZIP_PASSWORD: ${{ secrets.MYZIP_PASSWORD }}        
        
    - name: Unzip files with password
      uses: montudor/action-zip@v1
      with:
        args: unzip -P ${{ secrets.MYZIP_PASSWORD }} -qq channels.zip channels.csv
        
    - name: Run tests
      run: python scra.py
